{% set version = "1.2.1" %}
{% set name = "untangle" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae76522472722b31b303d5100c3c6f8b7dd4952b7b6c9d31e6d7b4a56f1a6d30

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - untangle

about:
  home: https://github.com/stchris/untangle
  license: MIT
  license_file: LICENSE
  summary: Convert XML documents into Python objects.
  doc_url: https://untangle.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - htenkanen
