{% set version = "1.2.0" %}
{% set name = "untangle" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dda75a60bfe69d76f116c3aea91c478885d25288d798f290201daa1400c1b5d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - untangle

about:
  home: https://github.com/stchris/untangle
  license: MIT
  license_file: LICENSE
  summary: Convert XML documents into Python objects.
  doc_url: https://untangle.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - htenkanen
